graph_planner:
  max_nodes: 20000
  steer_buffer_size: 5000
  cspace_similarity_threshold: 0.001

  sample_rejection_ratio: 10
  neighbors_per_node: 10
  feasibility_buffer_size: 2000
  new_nodes_per_iteration: 20

  max_path_finding_iterations: 4
  min_finetune_iterations: 2
  use_default_position_heuristic: true

  exploration_radius: 1.05
  exploration_radius_growth_factor: 1.05
  sampler_seed: 0
  sampler_buffer_size: 2000
  connect_terminal_nodes_with_nearest: false
  ellipsoid_projection_method: householder

  neighbors_per_node_growth_factor: 1.05
  new_nodes_per_iteration_growth_factor: 1.05

camera_route_policy:
  random_seed: 21
  max_attempts: 3
  enable_graph_attempt: 1
  num_ik_seeds: 8
  num_trajopt_seeds: 4
  position_tolerance_m: 0.005
  orientation_tolerance_rad: 0.05
